let verbsDetails = [
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
  {
    definition: "definition",
    synonyms: ["Synonym 1", "Synonym 2", "Synonym 3"],
    examples: ["Exemple 1", "Exemple 2"],
    images: ["https://placehold.co/100", "https://placehold.co/100"],
  },
];
